using System;

namespace NumberGuesser
{
    class Program
    {
        static void Main(string[] args)
        {
            int exit = 0;
            while (exit == 0)
            {
                Console.Title = "NumberGusser";
                Console.ForegroundColor = ConsoleColor.DarkGreen;
                Console.WriteLine("Welcome user in this game you should guess the number generated by random which is between 1 to 10");
                Console.ResetColor();
                Console.ForegroundColor = ConsoleColor.DarkYellow;
                Console.WriteLine("Guess the number !");
                Console.ResetColor();
                Random random = new Random();
                int correctNumber = random.Next(1, 10);
                string guessedNumberAsString = Console.ReadLine();
                try
                {
                    int gussedNumber = Int32.Parse(guessedNumberAsString);
                    if (correctNumber != gussedNumber)
                    {
                        Console.ForegroundColor = ConsoleColor.Red;
                        Console.WriteLine("Wrong guess! Try again (the game's correct number has just changed ! )");
                        Console.ResetColor();
                    }
                    else
                    {
                        Console.ForegroundColor = ConsoleColor.Cyan;
                        Console.WriteLine("You won ! if you want to exit type exit otherwise press any other key to continue ");
                        Console.Beep();
                        string answer = Console.ReadLine();
                        if (answer=="exit")
                        {
                            Console.Beep();
                            exit = 1;
                        }
                    }
                }
                catch
                {
                    Console.WriteLine("Please Enter a Number");
                }
            }
        }
    }
}
